baseURL: https://yjdong.art
title: Yan Jun Dong
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  subtitle: 董彦君 Yan Jun Dong
  copyright: All rights reserved. # todo: set your copyright type.
  author: Yan Jun Dong
  dontShowSource: true # please, do not do this :)
  portfolio:
    columns:
      desktop:
        archive: 6
        default: 3
      mobile:
        archive: 3
        default: 2
  socials:
    # todo: add your social accounts.
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/sharon_from_planet_b612'
      landing: true
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:yjdongart@gmail.com'
      landing: true
  homepage: "/work" # todo: uncomment homepage, homepage link is mostly same with menu.main[0]
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

# todo: uncomment menu.main array after you create contents.
menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: tags
      url: /tags/
      weight: 89
    - name: archive
      url: /tags/archive/
      weight: 90
    - name: about
      url: /about/
      weight: 91
